image: php:7.3

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: wol_soft_test
  MYSQL_USER: wol_soft_test
  MYSQL_PASSWORD: wol_soft_test

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
  - echo "Hallo"
  - mysql --version
