# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

services:
- mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wol_soft
  MYSQL_ROOT_PASSWORD: unittest

# We test PHP7.0
test:7.0:
  image: php:7.0
  script:
  - phpunit --configuration test/phpunit.xml --coverage-text