testing:
  script:
    - echo "Testing WOL-Soft with:"
    - phpunit --version
    - composer update
    - cd test
    - cp /var/gitlab-ci/testconf.php testconf.php
    - phpunit --bootstrap bootstrap.php --config phpunit.xml --coverage-text --colors=never
