stages:
  - build

build:
  stage: build
  script:
    - echo "<?php" > ../Conf.php
    - composer update -o --ignore-platform-reqs
    - php install/generateModels.php
    - npm install
    - grunt default
    - npm install --only=prod
    - composer update --no-dev -o --ignore-platform-reqs
  artifacts:
    name: "${CI_PIPELINE_ID}"
    paths:
      - htdocs
      - src
      - vendor
      - node_modules
      - Gruntfile.js
      - deploy.sh
      - index.js
      - composer.json
      - package.json
      - updateDB.php
      - updateDBconfig.php
    when: always
    expire_in: 1 day
  cache:
    key: wol-soft-pipeline-cache
    paths:
      - ./node_modules/
      - ./vendor/
