version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: beerplop-redis

  mysql:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: beerplop-mysql
    restart: always
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=beerplopRoot
      - MYSQL_DATABASE=beerplop
      - MYSQL_USER=beerplop
      - MYSQL_PASSWORD=beerplop
    ports:
      - "8082:3306"

  php:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile_php'
    depends_on:
      - mysql
    volumes:
      - .:/var/www/beerplop/
    container_name: beerplop-php

  apache:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile_apache'
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - .:/var/www/beerplop/
    container_name: beerplop-webserver
